# Feature Engineering

## What is Feature Engineering?

Feature engineering is the process of transforming raw data into meaningful inputs (called features) that machine learning models can use more effectively. Instead of feeding a model the dataset exactly as it was collected, we often modify existing variables, combine multiple variables, or create entirely new ones that better capture patterns in the data.

For example, a dataset might contain a person's date of birth, but a model may learn more effectively from a derived feature like age. Similarly, combining variables such as price and quantity into a new feature like total spending can help a model capture relationships that are not immediately visible in the original data.

Feature engineering plays an important role in both model performance and interpretability. Well-designed features help models detect meaningful patterns more easily, which can improve predictive accuracy. At the same time, features that represent clear real-world concepts make it easier for humans to understand how and why a model arrives at its predictions.

Because of this, feature engineering is often one of the most impactful steps in the data science workflow. In many cases, improving the features used by a model can lead to larger performance gains than simply switching to a more complex algorithm.

## Why is Feature Engineering Important?

Machine learning models do not learn directly from raw data, but rather they learn from the features we provide. The quality and structure of these features strongly influence how well a model can detect patterns and make predictions.

If the features capture the important relationships in the data, even relatively simple models can perform well. However, if the features are poorly constructed or fail to represent meaningful information, even advanced models may struggle to learn useful patterns.

This idea is often summarized by the principle “Garbage In, Garbage Out” (GIGO). A model's prediction is only as good as the data we put inside of it, so the feature engineering phase is critical to creating a good model.

By carefully designing and transforming features, we make it easier for models to understand the underlying structure of the data. As a result, good feature engineering can lead to more accurate models, faster training, and more interpretable predictions.

## Encoding Categorical Variables

Variables in a dataset generally fall into two categories: quantitative and categorical. Quantitative variables represent numerical values that have meaningful magnitudes, such as age, income, or temperature. Categorical variables represent discrete groups or labels, such as color, country, or type of product.

Most machine learning models require numerical inputs, which means categorical variables must be converted into numbers before a model can use them. This process is called encoding.

It is important that the encoding method preserves the meaning of the categories without introducing misleading relationships. For example, assigning numbers like 1, 2, and 3 to categories such as red, blue, and green might incorrectly suggest an ordering between them. Instead, techniques like one-hot encoding create separate binary columns for each category, allowing models to represent categories without implying a numerical relationship.

## One-hot Encoding vs Ordinal Encoding

Two common methods for converting categorical variables into numerical form are one-hot encoding and ordinal encoding. Each method is appropriate for different types of categorical data.

### Ordinal Encoding

Ordinal encoding assigns an integer value to each category. This method is appropriate when the categories have a natural order.

For example, education levels such as High School, Bachelor’s, and Master’s have an inherent ranking. Encoding them as 0, 1, 2 preserves this ordering.

In [1]:
import pandas as pd

df = pd.DataFrame({
    "education": ["High School", "Bachelors", "Masters", "Bachelors"]
})

mapping = {
    "High School": 0,
    "Bachelors": 1,
    "Masters": 2
}

df["education_encoded"] = df["education"].map(mapping)

df

     education  education_encoded
0  High School                  0
1    Bachelors                  1
2      Masters                  2
3    Bachelors                  1

Here, the model can learn from the fact that Master’s > Bachelor’s > High School.

However, ordinal encoding should not be used when categories have no meaningful order.

### One-hot Encoding

One-hot encoding creates a separate binary column for each category. A value of 1 indicates the presence of that category, while 0 indicates absence.

This method is appropriate for nominal categorical variables, where categories do not have an inherent order (e.g., colors or product types).

Here's an example:

In [2]:
df = pd.DataFrame({
    "color": ["red", "blue", "green", "blue"]
})

df_encoded = pd.get_dummies(df, columns=["color"])

df_encoded

   color_blue  color_green  color_red
0       False        False       True
1        True        False      False
2       False         True      False
3        True        False      False

This produces columns like:

color_blue,           color_green, and           color_red

Each row will have a 1 in the column corresponding to its category.

# Feature Scaling and Selection

## Why Feature Scaling Matters

Feature scaling adjusts numerical features so they are on a similar scale. This matters because many machine learning models are sensitive to the magnitude of input features.

If one feature ranges in the thousands (e.g., income) while another ranges between 0 and 1 (e.g., rating), the larger feature may dominate the learning process simply because of its scale.

Scaling is especially important for gradient-based models such as linear regression (with gradient descent), logistic regression, neural networks, and support vector machines. Large differences in feature scale can cause gradients to behave unevenly across dimensions, which can lead to slower or unstable convergence.

By scaling features to comparable ranges, optimization becomes more stable and models can learn faster and more effectively.

## Common Feature Scaling Methods

There are several common methods used to scale numerical features so they fall within comparable ranges.

### 1. Standardization (Z-score Scaling)

Standardization transforms data so that it has a mean of 0 and a standard deviation of 1. This method is commonly used in many machine learning models because it centers the data while preserving the distribution.

$$
x_{scaled} = \frac{x - \mu}{\sigma}
$$

Below, we standardize the age column by subtracting the mean and dividing by the standard deviation.

In [3]:
df = pd.DataFrame({
    "age": [22, 25, 30, 35, 40]
})

df["age_standardized"] = (df["age"] - df["age"].mean()) / df["age"].std()

df

   age  age_standardized
0   22         -1.150577
1   25         -0.739657
2   30         -0.054789
3   35          0.630078
4   40          1.314945

### 2. Min-Max Scaling

Min-max scaling rescales values so they fall within a fixed range, usually 0 to 1.

$$
x_{scaled} = \frac{x - x_{min}}{x_{max} - x_{min}}
$$

Here we rescale the age column so the smallest value becomes 0 and the largest becomes 1.

In [4]:
df["age_minmax"] = (df["age"] - df["age"].min()) / (df["age"].max() - df["age"].min())

df

   age  age_standardized  age_minmax
0   22         -1.150577    0.000000
1   25         -0.739657    0.166667
2   30         -0.054789    0.444444
3   35          0.630078    0.722222
4   40          1.314945    1.000000

### 3. Normalization

Normalization scales observations so that the vector length (L2 norm) equals 1. This is commonly used in applications like text processing or similarity-based models where the direction of the vector matters more than its magnitude.

In this example, we normalize the age column using the L2 norm.

In [5]:
import numpy as np

df["age_normalized"] = df["age"] / np.linalg.norm(df["age"])

df

   age  age_standardized  age_minmax  age_normalized
0   22         -1.150577    0.000000        0.316424
1   25         -0.739657    0.166667        0.359573
2   30         -0.054789    0.444444        0.431487
3   35          0.630078    0.722222        0.503402
4   40          1.314945    1.000000        0.575316

## What is Feature Selection?

Feature selection is the process of identifying and selecting the most relevant features in a dataset to use when training a machine learning model. Instead of using every available variable, feature selection focuses on keeping the features that provide useful information while removing those that are irrelevant, redundant, or noisy.

Feature selection is important because unnecessary features can make models more complex, harder to interpret, and more prone to overfitting. By reducing the number of features, we can simplify the model, improve interpretability, and sometimes even improve predictive performance. Additionally, using fewer features can reduce computational cost and make models faster to train.

## Feature Selection Methods

There are several approaches to selecting useful features. Two common categories are filter methods and embedded methods. These techniques help identify which features are most informative for predicting the target variable.

### Filter Methods

Filter methods evaluate features based on statistical properties of the data, independent of any machine learning model. A common example is using correlation to measure how strongly each feature is related to the target variable.

Below, we compute the correlation between each feature and the target variable and select the most correlated ones.

** Important Note: Filter methods are fast and simple, but they do not account for interactions between features.

In [6]:
df = pd.DataFrame({
    "age": [22, 25, 30, 35, 40],
    "income": [40, 50, 65, 80, 100],
    "hours_studied": [2, 3, 5, 6, 8],
    "exam_score": [60, 65, 75, 85, 95]
})

# Compute correlation with target
correlations = df.corr()["exam_score"].drop("exam_score")

# Select features with correlation above threshold
selected_features = correlations[abs(correlations) > 0.5]

selected_features

age              0.999714
income           0.998294
hours_studied    0.994637
Name: exam_score, dtype: float64

### Embedded Methods

Embedded methods perform feature selection as part of the model training process. Certain models automatically learn which features are most important.

For example, tree-based models such as Random Forests provide feature importance scores that indicate how useful each feature was during training.

Embedded methods often provide more reliable feature selection because the importance is learned directly from the model during training.

In [7]:
from sklearn.ensemble import RandomForestRegressor

X = df[["age", "income", "hours_studied"]]
y = df["exam_score"]

model = RandomForestRegressor(random_state=0)
model.fit(X, y)

# Feature importance
importance = pd.Series(model.feature_importances_, index=X.columns)

importance

age              0.320465
income           0.409837
hours_studied    0.269697
dtype: float64

## Tradeoffs Between Feature Engineering and Feature Selection

Feature engineering and feature selection both aim to improve how well a model learns from data. However, they introduce different tradeoffs related to model complexity, interpretability, and the risk of overfitting.

### Bias–Variance Tradeoff

Feature engineering often increases the number of features by creating new variables or interactions between variables. This can help models capture more complex patterns in the data, which may reduce bias.

However, adding many features can also increase variance, meaning the model may start fitting noise in the training data instead of real patterns. This can hurt performance on new, unseen data.

Feature selection works in the opposite direction. By removing unnecessary or redundant features, it simplifies the model and helps the model focus on the most useful information in the dataset.

### Interpretability vs Performance

Another tradeoff is between interpretability and predictive performance.

Highly engineered features or complex transformations may improve accuracy, but they can make it harder to understand what the model is doing. Simpler feature sets are usually easier to interpret, since each feature has a clearer meaning.

However, simpler models may sometimes miss useful patterns that more complex feature sets can capture.

### Risk of Overfitting

Using too many features can increase the risk of overfitting, where the model learns patterns specific to the training data that do not generalize well.

Feature selection helps reduce this risk by keeping only the most useful features and removing noisy or irrelevant ones.

In practice, data scientists often combine both approaches: they engineer useful features and then select the ones that contribute most to the model. This helps balance model performance with simplicity and generalization.

For example, if a dataset predicting house prices includes dozens of unnecessary features (such as random IDs or unrelated attributes), a model may learn patterns that only exist in the training data rather than real relationships.

 ## Key Takeaways

 - **Feature engineering** transforms raw data into useful features that help models learn patterns more effectively.
 - Good feature engineering can improve both **model performance** and **interpretability**.
 - Many machine learning models require **numerical inputs**, which is why categorical variables must be encoded using techniques like **one-hot encoding** or **ordinal encoding**.
 - **Feature scaling** ensures that numerical features are on similar ranges, helping gradient-based models train more efficiently.
 - **Feature selection** focuses on keeping the most relevant features while removing unnecessary or noisy ones.
 - In practice, data scientists often combine **feature engineering and feature selection** to balance model complexity, performance, and generalization.